---
# Separate Services Architecture: Flowable + Interaction Service
# Flowable runs independently, app connects via REST API

---
# Flowable Database
apiVersion: v1
kind: ConfigMap
metadata:
  name: flowable-db-config
  namespace: default
data:
  POSTGRES_DB: "flowable"
  POSTGRES_USER: "flowable"
  POSTGRES_PASSWORD: "flowable"

---
apiVersion: v1
kind: Secret
metadata:
  name: flowable-db-secret
  namespace: default
type: Opaque
data:
  password: Zmxvd2FibGU=  # flowable

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: flowable-postgres
  namespace: default
spec:
  serviceName: flowable-postgres
  replicas: 1
  selector:
    matchLabels:
      app: flowable-postgres
  template:
    metadata:
      labels:
        app: flowable-postgres
    spec:
      containers:
      - name: postgres
        image: postgres:13
        ports:
        - containerPort: 5432
        envFrom:
        - configMapRef:
            name: flowable-db-config
        - secretRef:
            name: flowable-db-secret
        volumeMounts:
        - name: flowable-postgres-storage
          mountPath: /var/lib/postgresql/data
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
  volumeClaimTemplates:
  - metadata:
      name: flowable-postgres-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 20Gi

---
apiVersion: v1
kind: Service
metadata:
  name: flowable-postgres
  namespace: default
spec:
  selector:
    app: flowable-postgres
  ports:
  - port: 5432
    targetPort: 5432
  clusterIP: None

---
# Flowable BPM Platform (Standalone)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flowable-platform
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flowable-platform
  template:
    metadata:
      labels:
        app: flowable-platform
    spec:
      containers:
      - name: flowable
        image: flowable/flowable-ui:7.0.1
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
          value: "org.postgresql.Driver"
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:postgresql://flowable-postgres:5432/flowable"
        - name: SPRING_DATASOURCE_USERNAME
          value: "flowable"
        - name: SPRING_DATASOURCE_PASSWORD
          value: "flowable"
        - name: FLOWABLE_COMMON_APP_IDM-ADMIN_USER
          value: "admin"
        - name: FLOWABLE_COMMON_APP_IDM-ADMIN_PASSWORD
          value: "test"
        volumeMounts:
        - name: bpmn-processes
          mountPath: /opt/flowable/work/
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /flowable-task
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /flowable-task
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
      volumes:
      - name: bpmn-processes
        configMap:
          name: bpmn-processes

---
apiVersion: v1
kind: Service
metadata:
  name: flowable-platform
  namespace: default
spec:
  selector:
    app: flowable-platform
  ports:
  - port: 80
    targetPort: 8080
  type: ClusterIP

---
# Application Database
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-db-config
  namespace: default
data:
  POSTGRES_DB: "interaction_service"
  POSTGRES_USER: "app_user"
  POSTGRES_PASSWORD: "app_password"

---
apiVersion: v1
kind: Secret
metadata:
  name: app-db-secret
  namespace: default
type: Opaque
data:
  password: YXBwX3Bhc3N3b3Jk  # app_password

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: app-postgres
  namespace: default
spec:
  serviceName: app-postgres
  replicas: 1
  selector:
    matchLabels:
      app: app-postgres
  template:
    metadata:
      labels:
        app: app-postgres
    spec:
      containers:
      - name: postgres
        image: postgres:13
        ports:
        - containerPort: 5432
        envFrom:
        - configMapRef:
            name: app-db-config
        - secretRef:
            name: app-db-secret
        volumeMounts:
        - name: app-postgres-storage
          mountPath: /var/lib/postgresql/data
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
  volumeClaimTemplates:
  - metadata:
      name: app-postgres-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 15Gi

---
apiVersion: v1
kind: Service
metadata:
  name: app-postgres
  namespace: default
spec:
  selector:
    app: app-postgres
  ports:
  - port: 5432
    targetPort: 5432
  clusterIP: None

---
# Kafka
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - name: kafka
        image: bitnami/kafka:3.5
        ports:
        - containerPort: 9092
        env:
        - name: KAFKA_CFG_NODE_ID
          value: "0"
        - name: KAFKA_CFG_PROCESS_ROLES
          value: "controller,broker"
        - name: KAFKA_CFG_CONTROLLER_QUORUM_VOTERS
          value: "0@kafka-0.kafka.default.svc.cluster.local:9093"
        - name: KAFKA_CFG_LISTENERS
          value: "PLAINTEXT://:9092,CONTROLLER://:9093"
        - name: KAFKA_CFG_ADVERTISED_LISTENERS
          value: "PLAINTEXT://kafka.default.svc.cluster.local:9092"
        - name: KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP
          value: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT"
        - name: KAFKA_CFG_CONTROLLER_LISTENER_NAMES
          value: "CONTROLLER"
        - name: KAFKA_CFG_INTER_BROKER_LISTENER_NAME
          value: "PLAINTEXT"
        - name: KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE
          value: "true"

---
apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: default
spec:
  selector:
    app: kafka
  ports:
  - port: 9092
    targetPort: 9092

---
# Interaction Service (connects to Flowable via REST API)
apiVersion: v1
kind: ConfigMap
metadata:
  name: interaction-service-config
  namespace: default
data:
  application.yaml: |
    spring:
      application:
        name: interaction-service
      datasource:
        url: jdbc:postgresql://app-postgres:5432/interaction_service
        username: app_user
        password: app_password
        driver-class-name: org.postgresql.Driver
      jpa:
        hibernate:
          ddl-auto: validate
        show-sql: false
      kafka:
        bootstrap-servers: kafka:9092
        producer:
          key-serializer: org.apache.kafka.common.serialization.StringSerializer
          value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
        consumer:
          group-id: interaction-service-group
          auto-offset-reset: earliest
          key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
          value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
          properties:
            spring.json.trusted.packages: "com.ngoctran.interactionservice.events"

    # Flowable REST API Configuration (no embedded Flowable)
    flowable:
      rest-api:
        url: http://flowable-platform  # Connect to separate Flowable service

    server:
      port: 8080

    logging:
      level:
        com.ngoctran.interactionservice: INFO

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: interaction-service
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: interaction-service
  template:
    metadata:
      labels:
        app: interaction-service
    spec:
      containers:
      - name: interaction-service
        image: ngoctran/interaction-service:latest
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "k8s"
        volumeMounts:
        - name: config-volume
          mountPath: /app/config
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
      volumes:
      - name: config-volume
        configMap:
          name: interaction-service-config

---
apiVersion: v1
kind: Service
metadata:
  name: interaction-service
  namespace: default
spec:
  selector:
    app: interaction-service
  ports:
  - port: 80
    targetPort: 8080
  type: ClusterIP

---
# BPMN Processes ConfigMap (for Flowable standalone)
apiVersion: v1
kind: ConfigMap
metadata:
  name: bpmn-processes
  namespace: default
binaryData:
  onboarding-process.bpmn: <base64-encoded-bpmn-file>

---
# Ingress for both services
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: services-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: flowable.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: flowable-platform
            port:
              number: 80
  - host: interaction-service.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: interaction-service
            port:
              number: 80

---
# Network Policies
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: flowable-network-policy
  namespace: default
spec:
  podSelector:
    matchLabels:
      app: flowable-platform
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: interaction-service
    ports:
    - protocol: TCP
      port: 8080

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: app-network-policy
  namespace: default
spec:
  podSelector:
    matchLabels:
      app: interaction-service
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from: []  # External access via Ingress
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: flowable-platform
    - podSelector:
        matchLabels:
          app: kafka
    - podSelector:
        matchLabels:
          app: app-postgres
    ports:
    - protocol: TCP
      port: 8080  # Flowable REST API
    - protocol: TCP
      port: 9092  # Kafka
    - protocol: TCP
      port: 5432  # App DB
